version: "3.9"

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  
    volumes:
      - .:/app  
    environment:
      - PYTHONUNBUFFERED=1  
      - KEY="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"
    restart: unless-stopped 
