version: "3.9"

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  
    volumes:
      - .:/app  
    environment:
      - PYTHONUNBUFFERED=1  
      - KEY_1=
      - KEY_2=
      - KEY_3=
      - KEY_4=
    restart: unless-stopped 
